app:
    resource: '@AppBundle/Controller/'
    type: annotation
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
astronaut:
    type:     rest
    resource: AppBundle\Controller\AstronautController